# Dependencies
```{r imports}

box::use(src / dirs[dirs])
box::use(compute = src / compute)
box::use(plt = src / plot)
box::use(brms[...])
box::use(readr[read_csv])
box::use(dplyr[...])
box::use(tidyr[spread, separate, gather, expand, nesting])
box::use(ggplot2[...])
box::use(scales[...])
box::use(terra[...])
box::use(geosphere[perimeter])
box::use(plyr[round_any])
box::use(ggtext[element_markdown])
box::use(tidybayes[...])
box::use(forcats[fct_relevel])
box::use(emmeans[...])
box::use(patchwork[...])
box::use(ggnewscale[...])
```

# Import data
```{r import-data}
data <- read_csv(file.path(
    dirs$resources, "bird_data", "full_dataset_2020-2021.csv"
))
dyad_data <- read_csv(file.path(
    dirs$resources, "bird_data", "dyad_dataset_2020-2021.csv"
))

data <- data %>% mutate(
    sharing_index = shared / total_rep,
    age = as.factor(age)
)
dyad_data <- dyad_data %>% mutate(
    sharing_index = shared / total_rep,
    imm_status = as.factor(wytham_born_1 + wytham_born_2)
)
```

# Model fitting
## Definitions

```{r}
# Repertoire size: residents vs immigrants
repsize_f <- brmsformula(
    repertoire_size ~ 1 +
        wytham_born + (1 | father),
    family = poisson()
)

# Acoustic similarity with neighbours: residents vs immigrants
acsim_neighbours_f <- brmsformula(
    mean_ac_sim ~ 1 +
        wytham_born * prop_immigrants + year + (1 | father),
    family = gaussian()
)
```


## Fit
```{r}

# Repertoire size: residents vs immigrants
repsize_m <-
    brm(
        formula = repsize_f,
        data = data,
        # prior = priors,
        iter = 4000, warmup = 1000,
        chains = 4,
        cores = 4,
        seed = 444,
        backend = "cmdstanr",
        # sample_prior = "only",
        file = file.path(dirs$model_fits, "repsize_m"),
        file_refit = "on_change",
        control = list(adapt_delta = 0.9999, max_treedepth = 30)
    )

# Acoustic similarity with neighbours: residents vs immigrants
acsim_neighbours_m <-
    brm(
        formula = acsim_neighbours_f,
        data = data,
        # prior = priors,
        iter = 4000, warmup = 1000,
        chains = 4,
        cores = 4,
        seed = 444,
        backend = "cmdstanr",
        # sample_prior = "only",
        file = file.path(dirs$model_fits, "acsim_neighbours_m"),
        file_refit = "on_change",
        control = list(adapt_delta = 0.9999, max_treedepth = 30)
    )
```

# Diagnostics and checks
```{r}
brms::hypothesis(acsim_neighbours_m, "wytham_bornTRUE:prop_immigrants < 0", robust = TRUE)
```

# Plots
```{r}
psetts <- list(
    text.colour = "#f2f2f2",
    background.colour = "#262626", # "transparent"
    text.size = 12,
    draw1 = "#c77426",
    draw2 = "#ad3b56",
    draw3 = "#5ca5b8"
)

labelcol <- c(psetts$draw1, psetts$draw2)
```


### Repertoire size: residents vs immigrants

```{r}

postpreds <- data %>%
    filter(wytham_born == wytham_born, repertoire_size == repertoire_size) %>%
    modelr::data_grid(wytham_born, father) %>%
    tidybayes::add_epred_draws(repsize_m, ndraws = 20)

postpreds %>%
    ggplot(aes(x = .epred)) +
    stat_pointinterval(
        data = postpreds, aes(color = wytham_born, x = .epred),
        point_size = 1.5, point_alpha = .5, interval_alpha = NA,
        interval_size = NA, fill = NA
    ) +
    stat_slab(
        data = postpreds, aes(color = wytham_born, x = .epred, group = .row),
        alpha = .4, size = .2, scale = 1, fill = NA
    ) +
    scale_colour_manual(
        name = "",
        labels = paste(
            "<span style='font-weight: bold !important; color:",
            shades::brightness(labelcol, 1.1),
            "'>",
            c("Immigrant", "Resident"),
            "</span>"
        ),
        values = labelcol
    ) +
    plt$settheme(
        back.fill = psetts$background.colour,
        text.size = psetts$text.size,
        text.colour = psetts$text.colour
    ) +
    guides(
        size = "none",
        color = guide_legend(override.aes = list(linetype = 0), reverse = TRUE)
    ) +
    coord_cartesian(xlim = c(2, 4), ylim = c(0, 1)) +
    labs(
        x = paste0(
            "Repertoire size <br>",
            "<span style='font-weight: bold !important; color:#9e9e9e'>",
            "(posterior predicted mean)</span>"
        ),
        y = "Density",
        title = "Immigration and\ncultural repertoire size",
        subtitle = "Posterior conditional effect<br>"
    ) +
    theme(
        plot.title = element_text(
            size = psetts$text.size + 2, colour = psetts$text.colour, face = "bold"
        ),
        plot.subtitle = ggtext::element_markdown(
            size = psetts$text.size, face = "italic"
        ),
        legend.key = element_rect(fill = NA),
        legend.box.background = element_blank(),
        legend.text = ggtext::element_markdown(size = 14),
        legend.position = c(.8, .8),
        axis.title.x.bottom = ggtext::element_markdown(
            colour = psetts$text.colour, size = psetts$text.size,
            margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0),
        )
    ) -> repsize_m_plot
```


## Acoustic similarity with neighbours: residents vs immigrants


```{r}

peffect <- "prop_immigrants:wytham_born"
acsim_neighbours_cond_effs <- brms::conditional_effects(
    acsim_neighbours_m,
    effects = peffect,
    spaghetti = T,
    points = T,
    ndraws = 150,
    resolution = 300,
    method = "posterior_epred"
)

acsim_neighbours_df <- as.data.frame(acsim_neighbours_cond_effs[[peffect]]) %>%
    attr("spaghetti") %>%
    tibble::as_tibble()

acsim_neighbours_df %>%
    ggplot(
        aes(
            x = effect1__,
            y = estimate__,
            group = sample__,
            colour = effect2__
        )
    ) +
    geom_line(alpha = .4, size = .2, show.legend = FALSE) +
    scale_colour_manual(
        name = "",
        labels = paste(
            "<span style='font-weight: bold !important; color:",
            labelcol,
            "'>",
            c("Immigrant", "Resident"),
            "</span>"
        ),
        values = labelcol,
    ) +
    ggnewscale::new_scale_colour() +
    geom_smooth(
        data = acsim_neighbours_df,
        aes(
            x = effect1__,
            y = estimate__,
            group = effect2__,
            color = effect2__
        ),
        method = "lm",
        alpha = .5,
        size = 1,
        se = FALSE,
        show.legend = FALSE
    ) +
    scale_colour_manual(
        name = "",
        labels = paste(
            "<span style='font-weight: bold !important; color:",
            rev(labelcol),
            "'>",
            c("Resident", "Immigrant"),
            "</span>"
        ),
        values = shades::brightness(labelcol, 1.1)
    ) +
    guides(
        size = "none",
        color = guide_legend(
            override.aes = list(linetype = 0),
            reverse = FALSE
        )
    ) +
    plt$settheme(
        back.fill = psetts$background.colour,
        text.size = psetts$text.size,
        text.colour = psetts$text.colour
    ) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    # coord_cartesian(xlim = c(2, 4), ylim = c(0, 1)) +
    labs(
        x = "Proportion of neighbours<br>that are immigrants",
        y = "Similarity with neighbours",
        title = "Immigration and\ncultural similarity",
        subtitle = "Posterior conditional effects<br>"
    ) +
    theme(
        plot.title = element_text(
            size = psetts$text.size + 2, colour = psetts$text.colour, face = "bold"
        ),
        plot.subtitle = ggtext::element_markdown(
            size = psetts$text.size, face = "italic"
        ),
        legend.key = element_rect(fill = NA),
        legend.box.background = element_blank(),
        legend.text = ggtext::element_markdown(size = 14),
        legend.position = c(.8, .8),
        axis.title.x.bottom = ggtext::element_markdown(
            colour = psetts$text.colour, size = psetts$text.size,
            margin = ggplot2::margin(t = 10, r = 0, b = 0, l = 0)
        )
    ) -> acsim_neighbours_plot
```

## Combine and save
```{r}
immplots <- repsize_m_plot + acsim_neighbours_plot +
    plot_layout(guides = "collect") &
    theme(
        plot.margin = unit(c(.8, .2, .8, .8), "cm"),
        plot.background =
            ggplot2::element_rect(fill = psetts$background.colour),
        legend.position = "right"
    )

# Save combined
ggsave(
    filename = "immplots.png",
    plot = immplots,
    path = dirs$figs,
    scale = 1,
    width = 24,
    height = 14,
    units = "cm",
    dpi = 350,
    limitsize = FALSE,
    bg = "transparent"
)
```